version: '3'
services:
  db:
    image: postgres:10.3-alpine
    env_file:
      - ./.env
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
  web:
    build: .
    command: npm run watch-server
    env_file:
      - ./.env
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  pgdata: {}
